const Info = () => {
    return (
        <div>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ac eros efficitur, dignissim felis a, vehicula tellus. Maecenas gravida risus ex, id pellentesque ex blandit non. Curabitur egestas rhoncus sapien, ut facilisis arcu rhoncus eu. Maecenas tristique elit a tortor pharetra, vitae elementum felis pulvinar. Morbi ultricies metus sed sodales mattis. Mauris ac neque non sapien congue sodales sit amet nec turpis. Nunc fermentum turpis id nibh malesuada, eu malesuada felis sollicitudin. Nulla rutrum ex nulla, non efficitur tellus mollis vel. Suspendisse potenti. Donec volutpat, magna sed fringilla dictum, mauris massa dictum nunc, eget malesuada urna ligula sit amet lectus. Aliquam pulvinar tincidunt leo et porttitor. Etiam felis massa, tempus non leo at, lacinia tincidunt libero. Suspendisse consequat, dolor sed condimentum malesuada, velit diam mattis velit, a imperdiet ligula nunc in ligula. Sed vehicula lacus libero, sit amet fermentum mi cursus quis. Nulla velit purus, condimentum quis tortor et, dictum finibus lacus. Quisque tellus felis, ornare in orci non, scelerisque suscipit velit.</p>

            <p>Pellentesque nisl lorem, efficitur vel mi dignissim, tempus commodo erat. Pellentesque nec rhoncus felis, id volutpat ipsum. Pellentesque aliquet diam a nisl volutpat, sit amet efficitur tellus sollicitudin. Vivamus nec consectetur velit. Cras mollis nibh at pulvinar venenatis. Fusce a felis rhoncus, maximus velit quis, sodales neque. Morbi faucibus ultrices nibh eget malesuada. Proin eu ultricies lectus, a pharetra nulla. Nam vestibulum tincidunt dignissim. Vivamus risus sapien, viverra non sem at, finibus ultrices justo. Donec tempus justo id libero tristique, vitae auctor ante ullamcorper. In et ipsum varius, pellentesque felis a, ultrices ante. Quisque id libero eget quam maximus interdum porta quis nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>

            <p>Quisque consequat ut magna a ullamcorper. Curabitur aliquam tempor ante, a sollicitudin felis posuere ac. Aenean nisi urna, vestibulum id efficitur quis, ullamcorper sit amet ipsum. Praesent volutpat elementum varius. Pellentesque laoreet quam ac quam auctor, nec fringilla nibh vehicula. Sed mattis nibh rhoncus, varius nisi id, mattis mauris. Donec tempor magna vitae magna mollis imperdiet vitae id massa. Nullam at ante odio. Proin placerat risus sapien, vitae fermentum purus efficitur quis. Duis molestie facilisis justo, et euismod sem lacinia at. Suspendisse potenti. Vestibulum dolor nulla, dictum eget ultrices molestie, laoreet ut lorem. Quisque ac nibh eros. Curabitur accumsan, ex in consectetur hendrerit, urna massa elementum massa, et elementum ligula eros vel justo. Duis interdum orci in rutrum sodales. Praesent sit amet euismod leo.</p>
        </div>
    )
}

export default Info